### Register an account
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "username": "peperoxyz",
    "email" : "peperoxyz@devscale.id",
    "password": "123456"
}

### Login User
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email" : "peperoxyz@devscale.id",
    "password": "123456"
}

### Access Protected Endpoint
GET http://localhost:3000/api/v1/protected
Authorization: Bearer cm19hptj7000t40uu6yze7hs7

### Logout Account
POST http://localhost:3000/api/v1/logout
Authorization: Bearer cm19hptj7000t40uu6yze7hs7