### Get All Quotes
GET http://localhost:3000/api/v1/quotes
Content-Type: application/json
token: myToken12345

### Create A Quotes
POST http://localhost:3000/api/v1/quotes
Content-Type: application/json

{
  "title": "If Something Worries You, Stop",
  "transcript": "You should never be worried about anything. You have solved problems in the past, and now you will too.",
  "author": "The Primeagen",
  "resource": "Youtube The Primeagen",
  "userId": "cm16f167b00002dtt8qtcx0g2",
  "categoryId": "cm16fbmqh0000modmspzbraee"
}
