import { jost } from "./ui/fonts";
import "./ui/globals.css";

export const metadata = {
	title: "Clippy Quote - Assignment 4 | Dea",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${jost.className} antialiased bg-primary`}>{children}</body>
		</html>
	);
}
